# Generated by Django 4.2.9 on 2024-09-12 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='username must be contained only A-Z a-z and _', regex='^[A-Za-z_]+$'), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
